In [1]:
import numpy as np

In [3]:
a=np.array([1,2,3])

In [4]:
print(type(a))

<class 'numpy.ndarray'>


In [5]:
print(a.shape)

(3,)


In [6]:
print(a[0],a[1],a[2])

1 2 3


In [7]:
a[0]=5

In [8]:
print(a)

[5 2 3]


In [10]:
b=np.array([[1,2,3],[4,5,6]])

In [11]:
print(b.shape)

(2, 3)


In [12]:
print(b[0,0],b[0,1],b[1,0])

1 2 4


In [13]:
a=np.zeros((2,2))

In [14]:
print(a)

[[0. 0.]
 [0. 0.]]


In [15]:
b=np.ones((2,2))

In [16]:
print(b)

[[1. 1.]
 [1. 1.]]


In [17]:
c=np.full((2,2),7)

In [18]:
print(c)

[[7 7]
 [7 7]]


In [19]:
d=np.eye(2)

In [20]:
print(d)

[[1. 0.]
 [0. 1.]]


In [21]:
e=np.random.random((2,2))

In [22]:
print(e)

[[0.8475956  0.18939458]
 [0.06816814 0.8512077 ]]


In [23]:
np.array(np.mat('1 2;3 4'))

array([[1, 2],
       [3, 4]])

In [24]:
np.array(np.mat('1 2;3 4'),subok=True)

matrix([[1, 2],
        [3, 4]])

In [25]:
a=np.arange(10)

In [26]:
print(a[2:5])

[2 3 4]


In [28]:
a=np.array([[1,2,3],[3,4,5],[4,7,9]])

In [29]:
print(a[1:])

[[3 4 5]
 [4 7 9]]


In [30]:
a=np.array([[1,2,3],[4,5,6],[7,6,5]])

In [32]:
print(a[...,1])

[2 5 6]


In [34]:
print(a[1,...])

[4 5 6]


In [36]:
print(a[...,1:])

[[2 3]
 [5 6]
 [6 5]]


In [37]:
x=np.array([[1,2],[3,4],[5,6]])

In [38]:
y=x[[0,1,2],[0,1,0]]

In [39]:
print(y)

[1 4 5]


In [42]:
x=np.array([[1,1,2],[3,4,5],[6,7,8],[9,10,11]])

In [43]:
print(x[x>5])

[ 6  7  8  9 10 11]
